-- Create products table
CREATE TABLE IF NOT EXISTS products (
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  slug VARCHAR(255) NOT NULL UNIQUE,
  short_description TEXT,
  description LONGTEXT,
  price DECIMAL(10,2) NOT NULL,
  discount_price DECIMAL(10,2),
  image_url VARCHAR(500),
  gallery JSON,
  stock INT DEFAULT 0,
  sku VARCHAR(100),
  brand VARCHAR(100),
  category VARCHAR(100),
  tags JSON,
  status ENUM('active', 'inactive', 'draft') DEFAULT 'draft',
  is_featured BOOLEAN DEFAULT FALSE,
  weight DECIMAL(8,2),
  dimensions JSON,
  meta_title VARCHAR(255),
  meta_description TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_slug (slug),
  INDEX idx_status (status),
  INDEX idx_category (category),
  INDEX idx_brand (brand),
  INDEX idx_sku (sku),
  INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 